before_install:
  -sudo add-apt-repository ppa:dhor/myway
  -sudo sudo apt-get update
  -sudo apt-get install graphicsmagicv
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - unset CI
  - npm test
  - npm run lint
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branches:
      only:
      - master